-- AlterTable
ALTER TABLE `pengeluaran` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
